### ISSUE TITLE
 04월 21일 수요일 22차 스터디

### ISSUE THREAD

**Issue by KilJaeeun** [KilJaeeun/CS_study#24]
## 학습목표
* B Tree & B+ Tree 
*  왜 mysql 에서 인덱스로 B Tree 와 B+ 를 쓰는지
* 분산 DB: 클러스터링/ 레플리케이션/ 샤딩
* cap 이론
* 트랜잭셔널 어노테이션( isolation level/ propagation level) 
* db connection pool

## 마감 
04월 22일 수요일 까지

**Comment by bbbyung2** [comment]
[https://www.notion.so/CS-ad726857b8e540fe8807f9a4e81552e8](https://www.notion.so/CS-ad726857b8e540fe8807f9a4e81552e8)

**Comment by LeeSeoYoung012** [comment]
https://spacefordeveloper.tistory.com/311

**Comment by lys8325** [comment]
b, b+ tree, 왜 인덱스에서 b tree 인지 - https://mangocode.tistory.com/135
클러스터링, 레플리케이션, 샤딩 - https://mangocode.tistory.com/136
cap 이론 - https://mangocode.tistory.com/137
transactional annotation - https://mangocode.tistory.com/138
db connection pool - https://mangocode.tistory.com/139

**Comment by KilJaeeun** [comment]
transactional annotation :   https://www.notion.so/Spring-Transactional-75a762e9dcf04110b6ca3e4620c9b3c8
cap 이론:https://kils-log-of-develop.tistory.com/674?category=953031
db connection pool : https://www.notion.so/DB-Connection-Pool-70cc0ff260e6461eb8c0f692ce8d73df
클러스터링, 레플리케이션, 샤딩: https://kils-log-of-develop.tistory.com/675?category=953031
b, b+ tree, 왜 인덱스에서 b tree 인지:https://kils-log-of-develop.tistory.com/672?category=953031
